from __future__ import annotations

from collections.abc import Sequence
from typing import ClassVar

def engine_health() -> bool: ...

class BlocusError(Exception): ...
class InputError(BlocusError): ...
class RuleViolationError(BlocusError): ...
class EngineError(BlocusError): ...

class PlayerColor:
    BLUE: ClassVar[PlayerColor]
    YELLOW: ClassVar[PlayerColor]
    RED: ClassVar[PlayerColor]
    GREEN: ClassVar[PlayerColor]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def blue() -> PlayerColor: ...
    @staticmethod
    def yellow() -> PlayerColor: ...
    @staticmethod
    def red() -> PlayerColor: ...
    @staticmethod
    def green() -> PlayerColor: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def index(self) -> int: ...

class GameStatus:
    IN_PROGRESS: ClassVar[GameStatus]
    FINISHED: ClassVar[GameStatus]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def in_progress() -> GameStatus: ...
    @staticmethod
    def finished() -> GameStatus: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

class ScoringMode:
    BASIC: ClassVar[ScoringMode]
    ADVANCED: ClassVar[ScoringMode]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def basic() -> ScoringMode: ...
    @staticmethod
    def advanced() -> ScoringMode: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

class GameMode:
    TWO_PLAYER: ClassVar[GameMode]
    THREE_PLAYER: ClassVar[GameMode]
    FOUR_PLAYER: ClassVar[GameMode]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def two_player() -> GameMode: ...
    @staticmethod
    def three_player() -> GameMode: ...
    @staticmethod
    def four_player() -> GameMode: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

class DomainEventKind:
    MOVE_APPLIED: ClassVar[DomainEventKind]
    PLAYER_PASSED: ClassVar[DomainEventKind]
    TURN_ADVANCED: ClassVar[DomainEventKind]
    GAME_FINISHED: ClassVar[DomainEventKind]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def move_applied() -> DomainEventKind: ...
    @staticmethod
    def player_passed() -> DomainEventKind: ...
    @staticmethod
    def turn_advanced() -> DomainEventKind: ...
    @staticmethod
    def game_finished() -> DomainEventKind: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

class DomainResponseKind:
    MOVE_APPLIED: ClassVar[DomainResponseKind]
    PLAYER_PASSED: ClassVar[DomainResponseKind]
    GAME_FINISHED: ClassVar[DomainResponseKind]

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def move_applied() -> DomainResponseKind: ...
    @staticmethod
    def player_passed() -> DomainResponseKind: ...
    @staticmethod
    def game_finished() -> DomainResponseKind: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...

class DomainEvent:
    @property
    def kind(self) -> DomainEventKind: ...
    @property
    def game_id(self) -> str: ...
    @property
    def version(self) -> int: ...

class DomainResponse:
    @property
    def kind(self) -> DomainResponseKind: ...
    @property
    def message(self) -> str: ...

class GameResult:
    @property
    def next_state(self) -> GameState: ...
    @property
    def events(self) -> list[DomainEvent]: ...
    @property
    def response(self) -> DomainResponse: ...

class SharedColorTurn:
    def __init__(self, color: PlayerColor, players: Sequence[str]) -> None: ...
    @property
    def color(self) -> PlayerColor: ...
    @property
    def players(self) -> list[str]: ...

class PlayerSlots:
    @staticmethod
    def two_player(
            blue_red_player: str,
            yellow_green_player: str,
    ) -> PlayerSlots: ...
    @staticmethod
    def three_player(
            owned_colors: Sequence[tuple[PlayerColor, str]],
            shared_color_turn: SharedColorTurn,
    ) -> PlayerSlots: ...
    @staticmethod
    def four_player(
            assignments: Sequence[tuple[PlayerColor, str]],
    ) -> PlayerSlots: ...

class GameConfig:
    def __init__(
            self,
            game_id: str,
            mode: GameMode,
            scoring: ScoringMode,
            turn_order: Sequence[PlayerColor],
            player_slots: PlayerSlots,
    ) -> None: ...
    @staticmethod
    def two_player(
            game_id: str,
            blue_red_player: str,
            yellow_green_player: str,
            scoring: ScoringMode,
    ) -> GameConfig: ...
    @staticmethod
    def four_player(
            game_id: str,
            assignments: Sequence[tuple[PlayerColor, str]],
            scoring: ScoringMode,
            turn_order: Sequence[PlayerColor],
    ) -> GameConfig: ...
    @property
    def game_id(self) -> str: ...
    @property
    def mode(self) -> GameMode: ...
    @property
    def scoring(self) -> ScoringMode: ...
    @property
    def turn_order(self) -> list[PlayerColor]: ...
    @property
    def player_slots(self) -> PlayerSlots: ...

class GameState:
    @property
    def schema_version(self) -> int: ...
    @property
    def game_id(self) -> str: ...
    @property
    def mode(self) -> GameMode: ...
    @property
    def scoring(self) -> ScoringMode: ...
    @property
    def status(self) -> GameStatus: ...
    @property
    def version(self) -> int: ...
    @property
    def hash(self) -> int: ...
    @property
    def board_is_empty(self) -> bool: ...
    @property
    def turn_order(self) -> list[PlayerColor]: ...
    @property
    def current_color(self) -> PlayerColor: ...
    @property
    def player_slots(self) -> PlayerSlots: ...

class PlaceCommand:
    def __init__(
            self,
            command_id: str,
            game_id: str,
            player_id: str,
            color: PlayerColor,
            piece_id: int,
            orientation_id: int,
            row: int,
            col: int,
    ) -> None: ...
    @property
    def command_id(self) -> str: ...
    @property
    def game_id(self) -> str: ...
    @property
    def player_id(self) -> str: ...
    @property
    def color(self) -> PlayerColor: ...
    @property
    def piece_id(self) -> int: ...
    @property
    def orientation_id(self) -> int: ...
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def board_index(self) -> int: ...

class PassCommand:
    def __init__(
            self,
            command_id: str,
            game_id: str,
            player_id: str,
            color: PlayerColor,
    ) -> None: ...
    @property
    def command_id(self) -> str: ...
    @property
    def game_id(self) -> str: ...
    @property
    def player_id(self) -> str: ...
    @property
    def color(self) -> PlayerColor: ...

class LegalMove:
    @property
    def piece_id(self) -> int: ...
    @property
    def orientation_id(self) -> int: ...
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def board_index(self) -> int: ...
    @property
    def score_delta(self) -> int: ...

class ScoreEntry:
    @property
    def player_id(self) -> str: ...
    @property
    def score(self) -> int: ...

class ScoreBoard:
    @property
    def scoring(self) -> ScoringMode: ...
    @property
    def entries(self) -> list[ScoreEntry]: ...

class BlocusEngine:
    def __init__(self) -> None: ...
    def initialize_game(self, config: GameConfig) -> GameState: ...
    def apply(
            self,
            state: GameState,
            command: PlaceCommand | PassCommand,
    ) -> GameResult: ...
    def get_valid_moves(
            self,
            state: GameState,
            player_id: str,
            color: PlayerColor,
    ) -> list[LegalMove]: ...
    def has_any_valid_move(
            self,
            state: GameState,
            player_id: str,
            color: PlayerColor,
    ) -> bool: ...
    def score_game(
            self,
            state: GameState,
            scoring: ScoringMode,
    ) -> ScoreBoard: ...