from __future__ import annotations

from typing import ClassVar, Final

def engine_health() -> bool: ...

class BlocusError(Exception):
    code: str
    category: str
    message: str

    def __init__(self, code: str, category: str, message: str) -> None: ...

class RuleViolationError(BlocusError): ...
class InputError(BlocusError): ...
class EngineError(BlocusError): ...

class PlayerColor:
    BLUE: ClassVar[Final[PlayerColor]]
    YELLOW: ClassVar[Final[PlayerColor]]
    RED: ClassVar[Final[PlayerColor]]
    GREEN: ClassVar[Final[PlayerColor]]

    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def index(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class GameStatus:
    IN_PROGRESS: ClassVar[Final[GameStatus]]
    FINISHED: ClassVar[Final[GameStatus]]

    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ScoringMode:
    BASIC: ClassVar[Final[ScoringMode]]
    ADVANCED: ClassVar[Final[ScoringMode]]

    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PlaceCommand:
    command_id: str
    game_id: str
    player_id: str
    color: PlayerColor
    piece_id: int
    orientation_id: int
    row: int
    col: int
    board_index: int

    def __init__(
        self,
        command_id: str,
        game_id: str,
        player_id: str,
        color: PlayerColor,
        piece_id: int,
        orientation_id: int,
        row: int,
        col: int,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PassCommand:
    command_id: str
    game_id: str
    player_id: str
    color: PlayerColor

    def __init__(
        self,
        command_id: str,
        game_id: str,
        player_id: str,
        color: PlayerColor,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
