from __future__ import annotations

from typing import ClassVar, Literal, final

def engine_health() -> bool: ...

class BlocusError(Exception):
    code: str
    category: str
    message: str

    def __init__(self, code: str, category: str, message: str) -> None: ...

class RuleViolationError(BlocusError): ...
class InputError(BlocusError): ...
class EngineError(BlocusError): ...

@final
class PlayerColor:
    BLUE: ClassVar[PlayerColor]
    YELLOW: ClassVar[PlayerColor]
    RED: ClassVar[PlayerColor]
    GREEN: ClassVar[PlayerColor]

    @property
    def name(self) -> Literal["BLUE", "YELLOW", "RED", "GREEN"]: ...
    @property
    def value(self) -> Literal["blue", "yellow", "red", "green"]: ...
    @property
    def index(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class GameStatus:
    IN_PROGRESS: ClassVar[GameStatus]
    FINISHED: ClassVar[GameStatus]

    @property
    def name(self) -> Literal["IN_PROGRESS", "FINISHED"]: ...
    @property
    def value(self) -> Literal["in_progress", "finished"]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class ScoringMode:
    BASIC: ClassVar[ScoringMode]
    ADVANCED: ClassVar[ScoringMode]

    @property
    def name(self) -> Literal["BASIC", "ADVANCED"]: ...
    @property
    def value(self) -> Literal["basic", "advanced"]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class PlaceCommand:
    def __init__(
        self,
        command_id: str,
        game_id: str,
        player_id: str,
        color: PlayerColor,
        piece_id: int,
        orientation_id: int,
        row: int,
        col: int,
    ) -> None: ...
    @property
    def command_id(self) -> str: ...
    @property
    def game_id(self) -> str: ...
    @property
    def player_id(self) -> str: ...
    @property
    def color(self) -> PlayerColor: ...
    @property
    def piece_id(self) -> int: ...
    @property
    def orientation_id(self) -> int: ...
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def board_index(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class PassCommand:
    def __init__(
        self,
        command_id: str,
        game_id: str,
        player_id: str,
        color: PlayerColor,
    ) -> None: ...
    @property
    def command_id(self) -> str: ...
    @property
    def game_id(self) -> str: ...
    @property
    def player_id(self) -> str: ...
    @property
    def color(self) -> PlayerColor: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
