//! Deterministic semantic hashing.
//!
//! The hash intentionally excludes `GameState::hash` itself and includes all
//! semantic state fields that affect gameplay, ownership, scoring, or replay.
//!
//! This module uses deterministic Zobrist-style pseudo-random constants derived
//! from fixed seeds. The constants are generated by `splitmix64`, which is fast,
//! stable, and adequate for game-state fingerprinting. This is not a
//! cryptographic hash.

use crate::{
    BOARD_SIZE, GameMode, GameState, GameStatus, PIECE_COUNT, PLAYER_COLOR_COUNT, PlayerColor,
    ScoringMode, StateVersion, ZobristHash,
};

/// Fixed domain seed for semantic state hashing.
pub const HASH_DOMAIN_SEED: u64 = 0x9e37_79b9_7f4a_7c15;

/// Hash value used for empty/zero semantic state fragments.
pub const HASH_EMPTY_SENTINEL: u64 = 0x6a09_e667_f3bc_c909;

/// Hash salt for occupied board cells.
pub const HASH_BOARD_CELL_SALT: u64 = 0xbb67_ae85_84ca_a73b;

/// Hash salt for piece inventory bits.
pub const HASH_INVENTORY_SALT: u64 = 0x3c6e_f372_fe94_f82b;

/// Hash salt for player/color ownership.
pub const HASH_PLAYER_SLOT_SALT: u64 = 0xa54f_f53a_5f1d_36f1;

/// Hash salt for turn-state fields.
pub const HASH_TURN_SALT: u64 = 0x510e_527f_ade6_82d1;

/// Hash salt for last-piece tracking.
pub const HASH_LAST_PIECE_SALT: u64 = 0x1f83_d9ab_fb41_bd6b;

/// Hash salt for identifiers.
pub const HASH_ID_SALT: u64 = 0x5be0_cd19_137e_2179;

/// Computes the full deterministic semantic hash for a game state.
///
/// The stored `state.hash` field is deliberately excluded, so this function is
/// stable for verification and round trips.
///
/// # Examples
///
/// ```
/// # use blocus_core::{BlocusEngine, GameConfig, GameId, GameMode, PlayerId, PlayerSlots, ScoringMode, TurnOrder, compute_hash_full};
/// # use uuid::Uuid;
/// # let game_id = GameId::from_uuid(Uuid::from_u128(1));
/// # let p1 = PlayerId::from_uuid(Uuid::from_u128(2));
/// # let p2 = PlayerId::from_uuid(Uuid::from_u128(3));
/// # let slots = PlayerSlots::two_player(p1, p2).unwrap();
/// # let config = GameConfig::try_new(game_id, GameMode::TwoPlayer, ScoringMode::Basic, TurnOrder::OFFICIAL_FIXED, slots).unwrap();
/// # let engine = BlocusEngine::new();
/// let state = engine.initialize_game(config);
/// assert_eq!(state.hash, compute_hash_full(&state));
/// ```
#[must_use]
pub fn compute_hash_full(state: &GameState) -> ZobristHash {
    let mut hash = HASH_DOMAIN_SEED;

    mix_u16(&mut hash, state.schema_version.as_u16());
    mix_uuid(&mut hash, state.game_id.as_uuid());
    mix_game_mode(&mut hash, state.mode);
    mix_scoring_mode(&mut hash, state.scoring);
    mix_turn_order(&mut hash, state.turn_order);
    mix_player_slots(&mut hash, state.player_slots);
    mix_board(&mut hash, state);
    mix_inventories(&mut hash, state);
    mix_u32_salted(
        &mut hash,
        HASH_LAST_PIECE_SALT,
        state.last_piece_by_color.packed(),
    );
    mix_turn_state(&mut hash, state);
    mix_game_status(&mut hash, state.status);
    mix_state_version(&mut hash, state.version);

    ZobristHash::new(hash)
}

/// Deterministic hash constant for one occupied board cell.
///
/// `bit_index` is the padded-row board bit index, not dense row-major index.
#[must_use]
pub const fn board_cell_hash(color: PlayerColor, bit_index: u16) -> u64 {
    splitmix64_const(HASH_BOARD_CELL_SALT ^ ((color_index_u64(color) + 1) << 48) ^ bit_index as u64)
}

/// Deterministic hash constant for one used piece bit in one color inventory.
#[must_use]
pub const fn inventory_piece_hash(color: PlayerColor, piece_id: u8) -> u64 {
    splitmix64_const(HASH_INVENTORY_SALT ^ ((color_index_u64(color) + 1) << 48) ^ piece_id as u64)
}

fn mix_board(hash: &mut u64, state: &GameState) {
    for color in PlayerColor::ALL {
        let lanes = state.board.occupied(color).lanes();

        for (lane_index, lane_value) in lanes.into_iter().enumerate() {
            let mut remaining = lane_value;

            while remaining != 0 {
                let offset = remaining.trailing_zeros();
                let bit_index = u16::try_from(lane_index * u128::BITS as usize + offset as usize)
                    .unwrap_or_else(|_| unreachable!("board bit index always fits in u16"));

                *hash ^= board_cell_hash(color, bit_index);
                remaining &= remaining - 1;
            }
        }
    }
}

fn mix_inventories(hash: &mut u64, state: &GameState) {
    for color in PlayerColor::ALL {
        let used_mask = state.inventories[color.index()].used_mask();

        for raw_piece_id in 0..PIECE_COUNT {
            if used_mask & (1u32 << raw_piece_id) != 0 {
                *hash ^= inventory_piece_hash(color, raw_piece_id);
            }
        }
    }
}

fn mix_player_slots(hash: &mut u64, slots: crate::PlayerSlots) {
    for color in PlayerColor::ALL {
        let color_index = u8::try_from(color.index())
            .unwrap_or_else(|_| unreachable!("player color index always fits in u8"));

        mix_u8_salted(hash, HASH_PLAYER_SLOT_SALT, color_index);

        match slots.controller_of(color) {
            Some(player_id) => {
                mix_u8(hash, 1);
                mix_uuid(hash, player_id.as_uuid());
            }
            None => mix_u8(hash, 0),
        }
    }

    match slots.shared_color_turn() {
        Some(shared) => {
            mix_u8(hash, 1);
            mix_player_color(hash, shared.color());

            for player_id in shared.players() {
                mix_uuid(hash, player_id.as_uuid());
            }
        }
        None => mix_u8(hash, 0),
    }
}

fn mix_turn_order(hash: &mut u64, turn_order: crate::TurnOrder) {
    for color in turn_order.colors() {
        mix_player_color(hash, color);
    }
}

fn mix_turn_state(hash: &mut u64, state: &GameState) {
    mix_u64_salted(
        hash,
        HASH_TURN_SALT,
        color_index_u64(state.turn.current_color()),
    );
    mix_u8_salted(hash, HASH_TURN_SALT, state.turn.passed_mask());
    mix_usize_salted(hash, HASH_TURN_SALT, state.turn.shared_color_turn_index());
}

fn mix_game_mode(hash: &mut u64, mode: GameMode) {
    let value = match mode {
        GameMode::TwoPlayer => 2,
        GameMode::ThreePlayer => 3,
        GameMode::FourPlayer => 4,
    };

    mix_u8(hash, value);
}

fn mix_scoring_mode(hash: &mut u64, scoring: ScoringMode) {
    let value = match scoring {
        ScoringMode::Basic => 0,
        ScoringMode::Advanced => 1,
    };

    mix_u8(hash, value);
}

fn mix_game_status(hash: &mut u64, status: GameStatus) {
    let value = match status {
        GameStatus::InProgress => 0,
        GameStatus::Finished => 1,
    };

    mix_u8(hash, value);
}

fn mix_player_color(hash: &mut u64, color: PlayerColor) {
    mix_u64(hash, color_index_u64(color));
}

fn mix_state_version(hash: &mut u64, version: StateVersion) {
    mix_u64(hash, version.as_u64());
}

fn mix_uuid(hash: &mut u64, uuid: uuid::Uuid) {
    let value = uuid.as_u128();
    let high = u64::try_from(value >> 64)
        .unwrap_or_else(|_| unreachable!("upper uuid bits fit in u64 after shift"));
    let low = u64::try_from(value & u128::from(u64::MAX))
        .unwrap_or_else(|_| unreachable!("lower uuid bits fit in u64 after mask"));

    mix_u64_salted(hash, HASH_ID_SALT, high);
    mix_u64_salted(hash, HASH_ID_SALT, low);
}

fn mix_u8(hash: &mut u64, value: u8) {
    mix_u64(hash, u64::from(value));
}

fn mix_u16(hash: &mut u64, value: u16) {
    mix_u64(hash, u64::from(value));
}

fn mix_u64(hash: &mut u64, value: u64) {
    *hash ^= splitmix64_const(value ^ HASH_EMPTY_SENTINEL);
    *hash = hash.rotate_left(17).wrapping_mul(0x94d0_49bb_1331_11eb);
}

fn mix_u8_salted(hash: &mut u64, salt: u64, value: u8) {
    mix_u64(hash, salt ^ u64::from(value));
}

fn mix_u32_salted(hash: &mut u64, salt: u64, value: u32) {
    mix_u64(hash, salt ^ u64::from(value));
}

fn mix_u64_salted(hash: &mut u64, salt: u64, value: u64) {
    mix_u64(hash, salt ^ value);
}

fn mix_usize_salted(hash: &mut u64, salt: u64, value: usize) {
    let value =
        u64::try_from(value).unwrap_or_else(|_| unreachable!("turn index should fit in u64"));

    mix_u64(hash, salt ^ value);
}

const fn color_index_u64(color: PlayerColor) -> u64 {
    match color {
        PlayerColor::Blue => 0,
        PlayerColor::Yellow => 1,
        PlayerColor::Red => 2,
        PlayerColor::Green => 3,
    }
}

const fn splitmix64_const(mut value: u64) -> u64 {
    value = value.wrapping_add(0x9e37_79b9_7f4a_7c15);
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}

const _: () = {
    assert!(PLAYER_COLOR_COUNT == 4);
    assert!(BOARD_SIZE == 20);
};
